 export const resetForm = (
  setObjValues,
  setVitalSignDto,
  setTbObj,
  setTests
) => {
  setObjValues({
    adherenceLevel: "",
    adheres: {},
    adrScreened: "",
    adverseDrugReactions: {},
    artStatusId: "",
    cd4: "",
    cd4Percentage: "",
    clinicalNote: "",
    clinicalStageId: "",
    facilityId: 0,
    functionalStatusId: "",
    hivEnrollmentId: "",
    nextAppointment: "",
    lmpDate: "",
    oiScreened: "",
    opportunisticInfections: {},
    personId: patientObj.id,
    tbScreen: {},
    stiIds: "",
    stiTreated: "",
    uuid: "",
    visitDate: "",
    whoStagingId: "",
    cryptococcalScreeningStatus: "",
    cervicalCancerScreeningStatus: "",
    cervicalCancerTreatmentProvided: "",
    hepatitisScreeningResult: "",
    familyPlaning: "",
    onFamilyPlaning: "",
    levelOfAdherence: "",
    tbStatus: "",
    tbPrevention: "",
    arvdrugsRegimen: {},
    viralLoadOrder: {},
    pregnancyStatus: "",
  });
  setVitalSignDto({
    bodyWeight: "",
    diastolic: "",
    encounterDate: "",
    facilityId: 1,
    height: "",
    personId: props.patientObj.id,
    serviceTypeId: 1,
    systolic: "",
    pulse: "",
    temperature: "",
    respiratoryRate: "",
    headCircumference: "",
    surfaceArea: "",
    nextAppointment: "",
    muac: "",
  });
  setTbObj({
    currentOnIpt: "",
    coughing: "",
    antiTBDrug: "",
    nightSweat: "",
    fever: "",
    contactWithTBCase: "",
    lethergy: "",
    tbStatusId: "",
  });

  setTests({
    comments: "",
    dateAssayed: "",
    labNumber: "",
    labTestGroupId: "",
    labTestId: "",
    dateResultReceived: "",
    patientId: props.patientObj ? props.patientObj.id : "",
    result: "",
    sampleCollectionDate: null,
    viralLoadIndication: "",
    visitId: "",
  });
};
