
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_METHOD_PROVIDED', 'Oral Pills', 'en', '', 'FP_METHOD_ORAL_PILLS', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_METHOD_PROVIDED', 'Injectable', 'en', '', 'FP_METHOD_INJECTABLE', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_METHOD_PROVIDED', 'IUD', 'en', '', 'FP_METHOD_IUD', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_METHOD_PROVIDED', 'Condoms', 'en', '', 'FP_METHOD_CONDOMS', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_METHOD_PROVIDED', 'Implants', 'en', '', 'FP_METHOD_IMPLANTS', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_METHOD_PROVIDED', 'Voluntary Sterilization', 'en', '', 'FP_METHOD_VOLUNTARY_STERILIZATION', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_METHOD_PROVIDED', 'Natural Methods', 'en', '', 'FP_METHOD_NATURAL_METHODS', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_TYPE_OF_CLIENT', 'PAC', 'en', '', 'FP_TYPE_OF_CLIENT_PAC', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_TYPE_OF_CLIENT', 'PPFP', 'en', '', 'FP_TYPE_OF_CLIENT_PPFP', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_TYPE_OF_CLIENT', 'Routine', 'en', '', 'FP_TYPE_OF_CLIENT_ROUTINE', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_SOURCE_OF_REFERRAL', 'PNC = Postnatal Clinic', 'en', '', 'FP_SOURCE_OF_REFERRAL_PNC', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_SOURCE_OF_REFERRAL', 'HCT = Counselling and Testing Clinic', 'en', '', 'FP_SOURCE_OF_REFERRAL_HCT', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_SOURCE_OF_REFERRAL', 'S = Self Referral', 'en', '', 'FP_SOURCE_OF_REFERRAL_S', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_SOURCE_OF_REFERRAL', 'STDC = STD Clinic', 'en', '', 'FP_SOURCE_OF_REFERRAL_STDC', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_SOURCE_OF_REFERRAL', 'ART = ART Clinic', 'en', '', 'FP_SOURCE_OF_REFERRAL_ART', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_SOURCE_OF_REFERRAL', 'PMTCT = PMTCT Clinic', 'en', '', 'FP_SOURCE_OF_REFERRAL_PMTCT', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_SOURCE_OF_REFERRAL', 'PPMV = Proprietary Patient Medicine Vendors', 'en', '', 'FP_SOURCE_OF_REFERRAL_PPMV', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_SOURCE_OF_REFERRAL', 'CP = Community Pharmacy', 'en', '', 'FP_SOURCE_OF_REFERRAL_CP', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_SOURCE_OF_REFERRAL', 'PPFP = Post-Partum Family Planning', 'en', '', 'FP_SOURCE_OF_REFERRAL_PPFP', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_SOURCE_OF_REFERRAL', 'PAC = Post Abortion Care', 'en', '', 'FP_SOURCE_OF_REFERRAL_PAC', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_SOURCE_OF_REFERRAL', 'CBD = Community Based Distributor', 'en', '', 'FP_SOURCE_OF_REFERRAL_CBD', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_CLIENT_STATUS', 'New Acceptor (NA)', 'en', '', 'FP_CLIENT_STATUS_NA', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_CLIENT_STATUS', 'Revisit (RV)', 'en', '', 'FP_CLIENT_STATUS_RV', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_NAME_OF_INJECTABLE', 'DMPA-IM', 'en', '', 'FP_NAME_OF_INJECTABLE_DMPA_IM', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_NAME_OF_INJECTABLE', 'NOR (Noristerat/Norigynon)', 'en', '', 'FP_NAME_OF_INJECTABLE_NOR', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_INJECTABLE_ROUTE', 'Provider-administered self-injectable (DMPA-SC)', 'en', '', 'FP_INJECTABLE_ROUTE_PROVIDER_ADMINISTERED', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_INJECTABLE_ROUTE', 'Self-Injection (DMPA-SC only)', 'en', '', 'FP_INJECTABLE_ROUTE_SELF_INJECTION', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_TYPE_OF_IUD', 'H (Hormonal)', 'en', '', 'FP_TYPE_OF_IUD_H', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_TYPE_OF_IUD', 'C (Copper)', 'en', '', 'FP_TYPE_OF_IUD_C', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_ACTION', 'Insertion (IN)', 'en', '', 'FP_ACTION_IN', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_ACTION', 'Removal (OUT)', 'en', '', 'FP_ACTION_OUT', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_TYPE_OF_CONDOM', 'Male (M)', 'en', '', 'FP_TYPE_OF_CONDOM_M', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_TYPE_OF_CONDOM', 'Female (F)', 'en', '', 'FP_TYPE_OF_CONDOM_F', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_TYPE_OF_IMPLANT', 'IMP (Implanon)', 'en', '', 'FP_TYPE_OF_IMPLANT_IMP', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_TYPE_OF_IMPLANT', 'JD (Jadelle)', 'en', '', 'FP_TYPE_OF_IMPLANT_JD', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_STERILIZATION_SEX', 'Male', 'en', '', 'FP_STERILIZATION_SEX_MALE', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_STERILIZATION_SEX', 'Female', 'en', '', 'FP_STERILIZATION_SEX_FEMALE', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_NATURAL_METHOD', 'Cycle Beads', 'en', '', 'FP_NATURAL_METHOD_CYCLE_BEADS', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_NATURAL_METHOD', 'Others', 'en', '', 'FP_NATURAL_METHOD_OTHERS', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_NATURAL_METHOD_OTHERS', 'OVM = Ovulation Mucus', 'en', '', 'FP_NATURAL_METHOD_OTHERS_OVM', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_NATURAL_METHOD_OTHERS', 'STT = Symptothermal', 'en', '', 'FP_NATURAL_METHOD_OTHERS_STT', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_NATURAL_METHOD_OTHERS', 'LAM = Lactational Amenorrhea Method', 'en', '', 'FP_NATURAL_METHOD_OTHERS_LAM', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);

INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_REFERRED_OUT', 'OR = Oral Pills', 'en', '', 'FP_REFERRED_OUT_OR', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_REFERRED_OUT', 'IJ = Injectable', 'en', '', 'FP_REFERRED_OUT_IJ', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
-- "IP" has no definition anywhere in the NHMIS register's KEY section (checked all glossary
-- rows) or the requirement doc — left as the bare code pending confirmation with the BA team.
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_REFERRED_OUT', 'IP', 'en', '', 'FP_REFERRED_OUT_IP', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_REFERRED_OUT', 'IUD = Intra-Uterine Device', 'en', '', 'FP_REFERRED_OUT_IUD', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_REFERRED_OUT', 'SR = Surgical Referred (STER)', 'en', '', 'FP_REFERRED_OUT_SR', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
INSERT INTO base_application_codeset (codeset_group, display, language, version, code, date_created, created_by, date_modified, modified_by, archived) VALUES ('FP_REFERRED_OUT', 'MR = Medical Referral', 'en', '', 'FP_REFERRED_OUT_MR', '2026-09-16 00:00:00', 'guest@lamisplus.org', '2026-09-16 00:00:00', 'guest@lamisplus.org', 0);
